"""JPL Horizons API wrapper for cross-validation reference.

Returns SSB-centered state vectors (ICRF / J2000 mean equator) matching the
local DE440 evaluator's units (meters, m/s). Used in P4 to confirm the DE440
preprocessor agrees with JPL's own published values.

Conventions:
  - location ``"@0"`` -> Solar System Barycenter (SSB)
  - refplane ``"earth"`` -> J2000 mean equator (= ICRF within ~23 mas frame bias).
    The DE440 evaluator output also lives in this frame.
  - Time scale: TDB (Horizons accepts ``epochs=jd_tdb`` as TDB by default).
  - Light-time correction: not applied (geometric position).
  - Output unit: AU / AU per day -> meters / meters per second using
    ``orbitarium_tools.constants.AU``.

The TS Horizons client (CORS proxy, browser caching) is intentionally deferred
to Work 7 (Orbits) where asteroids/comets/spacecraft drive the need; in Work 3
this Python wrapper is the only Horizons consumer.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from astroquery.jplhorizons import Horizons  # type: ignore[import-untyped]

from orbitarium_tools.constants import AU
from orbitarium_tools.de440 import PLANET_BODY_ALIASES
from orbitarium_tools.ephemeris import StateVectorICRF

SECONDS_PER_DAY = 86400.0


@dataclass(frozen=True, slots=True)
class HorizonsQueryResult:
    naif_id: int
    requested_naif_id: int
    jd_tdb: float
    state: StateVectorICRF


def _resolve_horizons_id(naif_id: int) -> int:
    """Apply the same outer-planet alias DE440 uses (Mars+ -> barycenter)."""
    return PLANET_BODY_ALIASES.get(naif_id, naif_id)


def query_state(naif_id: int, jd_tdb: float) -> HorizonsQueryResult:
    """Fetch a single SSB-centered state vector from Horizons.

    Always queries with ``refplane="earth"`` (J2000 mean equator / ICRF) and
    ``location="@0"`` (SSB). astroquery handles HTTP caching automatically.
    """
    horizons_id = _resolve_horizons_id(naif_id)
    obj = Horizons(id=str(horizons_id), location="@0", epochs=jd_tdb)
    vectors = obj.vectors(refplane="earth")
    row = vectors[0]
    px = float(row["x"]) * AU
    py = float(row["y"]) * AU
    pz = float(row["z"]) * AU
    vx = float(row["vx"]) * AU / SECONDS_PER_DAY
    vy = float(row["vy"]) * AU / SECONDS_PER_DAY
    vz = float(row["vz"]) * AU / SECONDS_PER_DAY
    return HorizonsQueryResult(
        naif_id=naif_id,
        requested_naif_id=horizons_id,
        jd_tdb=jd_tdb,
        state=StateVectorICRF(
            naif_id=naif_id,
            jd_tdb=jd_tdb,
            position=(px, py, pz),
            velocity=(vx, vy, vz),
        ),
    )


def query_states(
    naif_ids: Iterable[int], jd_tdbs: Iterable[float]
) -> list[HorizonsQueryResult]:
    """Convenience batch helper. Sequential calls to ``query_state``."""
    naif_id_list = list(naif_ids)
    jd_list = list(jd_tdbs)
    return [query_state(nid, jd) for nid in naif_id_list for jd in jd_list]


def cli_describe(result: HorizonsQueryResult) -> str:
    """Format a HorizonsQueryResult for the ``horizons`` CLI subcommand."""
    s = result.state
    alias_suffix = (
        f" (-> {result.requested_naif_id})"
        if result.requested_naif_id != result.naif_id
        else ""
    )
    return (
        f"NAIF {result.naif_id}{alias_suffix} @ JD TDB {result.jd_tdb}\n"
        f"  position (m) : ({s.position[0]: .6e}, {s.position[1]: .6e}, {s.position[2]: .6e})\n"
        f"  velocity (m/s): ({s.velocity[0]: .6e}, {s.velocity[1]: .6e}, {s.velocity[2]: .6e})"
    )


def generate_fixtures(out_dir: Path) -> Path:
    """Generate ``horizons-states.json`` for cross-validation in P6.

    Small grid (planets only at a few JDs) — Horizons is rate-limited so we
    keep the request count low. Cached automatically by astroquery.
    """
    import json

    out_dir.mkdir(parents=True, exist_ok=True)
    bodies = (10, 1, 2, 3, 4, 5, 6, 7, 8, 9)
    jds = (2451545.0, 2461165.5008007577, 2506717.5)
    fixtures: list[dict[str, object]] = []
    for body in bodies:
        for jd in jds:
            res = query_state(body, jd)
            fixtures.append(
                {
                    "naif_id": res.naif_id,
                    "horizons_naif_id": res.requested_naif_id,
                    "jd_tdb": jd,
                    "position_m": list(res.state.position),
                    "velocity_m_s": list(res.state.velocity),
                }
            )
    output: dict[str, object] = {
        "_comment": (
            "Generated by orbitarium_tools.horizons.generate_fixtures. "
            "Re-run: orbitarium-tools fixtures --work=3 --out=tests/fixtures/work-03/"
        ),
        "_source": (
            "JPL Horizons API (astroquery), refplane='earth' (J2000 mean equator), "
            "location='@0' (SSB), light-time off."
        ),
        "_tolerance_m": 1e-2,
        "_tolerance_vel_m_s": 1e-6,
        "fixtures": fixtures,
    }
    out_path = out_dir / "horizons-states.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)
        f.write("\n")
    return out_path


__all__ = [
    "HorizonsQueryResult",
    "cli_describe",
    "generate_fixtures",
    "query_state",
    "query_states",
]
