"""Scene anchor reference implementation (Work 5 P3).

Mirrors ``src/render/anchors.ts``. Pure functions on ICRF positions (m):

- ``ssb``: identity (Solar System Barycenter is the truth-frame origin).
- ``heliocentric``: shift origin to the Sun's SSB position.
- ``body-centric``: shift origin to a given body's SSB position.

Composed with :func:`orbitarium_tools.scaling.position_to_scene` for scene
output, and (in the browser) further multiplied by the
``SCENE_TO_THREE_UNIT_RATIO`` constant for ``THREE.Vector3`` world coords.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

PositionM = tuple[float, float, float]

AnchorKind = Literal["ssb", "heliocentric", "body-centric"]


@dataclass(frozen=True, slots=True)
class SceneAnchorContext:
    kind: AnchorKind
    reference_ssb_m: PositionM | None = None


def ssb_anchor() -> SceneAnchorContext:
    return SceneAnchorContext(kind="ssb", reference_ssb_m=None)


def heliocentric_anchor(sun_ssb_m: Sequence[float]) -> SceneAnchorContext:
    return SceneAnchorContext(
        kind="heliocentric",
        reference_ssb_m=(float(sun_ssb_m[0]), float(sun_ssb_m[1]), float(sun_ssb_m[2])),
    )


def body_centric_anchor(body_ssb_m: Sequence[float]) -> SceneAnchorContext:
    return SceneAnchorContext(
        kind="body-centric",
        reference_ssb_m=(float(body_ssb_m[0]), float(body_ssb_m[1]), float(body_ssb_m[2])),
    )


def apply_anchor(
    position_icrf_m: Sequence[float],
    anchor: SceneAnchorContext,
) -> PositionM:
    p: PositionM = (
        float(position_icrf_m[0]),
        float(position_icrf_m[1]),
        float(position_icrf_m[2]),
    )
    if anchor.kind == "ssb":
        return p
    ref = anchor.reference_ssb_m
    if ref is None:
        raise ValueError(f"anchor kind {anchor.kind!r} requires reference_ssb_m")
    return (p[0] - ref[0], p[1] - ref[1], p[2] - ref[2])


SAMPLE_SUN_SSB_M: PositionM = (1_000_000_000.0, -500_000_000.0, 0.0)
SAMPLE_EARTH_SSB_M: PositionM = (
    SAMPLE_SUN_SSB_M[0] + 149_597_870_700.0,
    SAMPLE_SUN_SSB_M[1],
    SAMPLE_SUN_SSB_M[2],
)

SAMPLE_POSITIONS: list[tuple[str, PositionM]] = [
    ("zero", (0.0, 0.0, 0.0)),
    ("sun_ssb", SAMPLE_SUN_SSB_M),
    ("earth_ssb_aligned", SAMPLE_EARTH_SSB_M),
    ("mars_x_axis", (227_900_000_000.0, 0.0, 0.0)),
    ("jupiter_y_axis", (0.0, 778_300_000_000.0, 0.0)),
    ("pluto_z_axis", (0.0, 0.0, 5_900_000_000_000.0)),
]


def generate_anchor_fixtures(out_dir: Path | str) -> Path:
    """Anchor x sample positions -> applied positions table."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    anchors: dict[str, SceneAnchorContext] = {
        "ssb": ssb_anchor(),
        "heliocentric": heliocentric_anchor(SAMPLE_SUN_SSB_M),
        "body-centric_earth": body_centric_anchor(SAMPLE_EARTH_SSB_M),
    }

    out_anchors: list[dict[str, object]] = []
    for name, ctx in anchors.items():
        rows = []
        for sample_name, pos in SAMPLE_POSITIONS:
            applied = apply_anchor(pos, ctx)
            rows.append(
                {
                    "sample": sample_name,
                    "position_icrf_m": list(pos),
                    "applied_m": list(applied),
                }
            )
        entry: dict[str, object] = {"name": name, "kind": ctx.kind, "samples": rows}
        if ctx.reference_ssb_m is not None:
            entry["reference_ssb_m"] = list(ctx.reference_ssb_m)
        out_anchors.append(entry)

    output: dict[str, object] = {
        "_comment": (
            "Generated by orbitarium_tools.render_anchors.generate_anchor_fixtures. "
            "Re-run: orbitarium-tools fixtures --work=5 --out=tests/fixtures/work-05/"
        ),
        "_source": (
            "Scene anchor (SSB / Heliocentric / Body-centric) applied to "
            "sample ICRF positions. Heliocentric uses Sun ~1.5e9 m offset "
            "from SSB; body-centric uses Earth at 1 AU + sun offset."
        ),
        "_tolerance_mm": 1.0,
        "anchors": out_anchors,
    }
    out_path = out_dir / "scene-anchors.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)
        f.write("\n")
    return out_path
