"""Validation reporting (Work 12).

Compares DE440 (cached SPK) vs JPL Horizons live API for a small
body x time matrix. Produces JSON + Markdown reports.

The actual Horizons calls are exercised by ``orbitarium-tools horizons``
(Work 3) — this module focuses on the matrix orchestration + summary.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Final


@dataclass(frozen=True, slots=True)
class ValidationSample:
    body_key: str
    utc_iso: str
    jd_tdb: float
    de440_position_m: tuple[float, float, float]
    horizons_position_m: tuple[float, float, float] | None
    diff_magnitude_m: float | None
    angular_error_mas: float | None


def magnitude(v: tuple[float, float, float]) -> float:
    return math.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2)


def angular_separation_mas(
    a: tuple[float, float, float], b: tuple[float, float, float]
) -> float:
    """Angular separation between two position vectors, in milli-arcseconds."""
    am = magnitude(a)
    bm = magnitude(b)
    if am == 0.0 or bm == 0.0:
        return 0.0
    cos_theta = (a[0] * b[0] + a[1] * b[1] + a[2] * b[2]) / (am * bm)
    cos_theta = max(-1.0, min(1.0, cos_theta))
    theta_rad = math.acos(cos_theta)
    return theta_rad * (180.0 / math.pi) * 3_600_000.0


def diff_magnitude_m(
    a: tuple[float, float, float], b: tuple[float, float, float]
) -> float:
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2)


def summarize(samples: list[ValidationSample]) -> dict[str, object]:
    bodies = {s.body_key for s in samples}
    finite = [s for s in samples if s.diff_magnitude_m is not None]
    if not finite:
        return {
            "bodies": len(bodies),
            "samples": len(samples),
            "mean_diff_m": None,
            "max_diff_m": None,
        }
    diffs = [s.diff_magnitude_m for s in finite if s.diff_magnitude_m is not None]
    angs = [s.angular_error_mas for s in finite if s.angular_error_mas is not None]
    return {
        "bodies": len(bodies),
        "samples": len(samples),
        "mean_diff_m": sum(diffs) / len(diffs),
        "max_diff_m": max(diffs),
        "mean_angular_mas": sum(angs) / len(angs) if angs else None,
        "max_angular_mas": max(angs) if angs else None,
    }


VALIDATION_TARGETS: Final[tuple[tuple[str, int], ...]] = (
    ("mercury", 199),
    ("venus", 299),
    ("earth", 399),
    ("mars", 499),
    ("jupiter", 599),
)

VALIDATION_TIMES: Final[tuple[str, ...]] = (
    "2000-01-01T12:00:00Z",
    "2024-04-08T18:18:00Z",
    "2026-05-06T00:00:00Z",
)


def write_report(samples: list[ValidationSample], out_dir: Path) -> tuple[Path, Path]:
    """Emit JSON + Markdown side-by-side."""
    out_dir.mkdir(parents=True, exist_ok=True)
    summary = summarize(samples)

    json_payload: dict[str, object] = {
        "_comment": "Generated by orbitarium-tools validate --report.",
        "_generated_at": "2026-05-06T00:00:00Z",
        "summary": summary,
        "samples": [
            {
                "body_key": s.body_key,
                "utc_iso": s.utc_iso,
                "jd_tdb": s.jd_tdb,
                "de440_position_m": list(s.de440_position_m),
                "horizons_position_m": (
                    list(s.horizons_position_m) if s.horizons_position_m else None
                ),
                "diff_magnitude_m": s.diff_magnitude_m,
                "angular_error_mas": s.angular_error_mas,
            }
            for s in samples
        ],
    }

    json_path = out_dir / "validation.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(json_payload, f, indent=2)
        f.write("\n")

    md_lines = [
        "# Orbitarium Validation Report",
        "",
        f"Generated: {json_payload['_generated_at']}",
        "",
        "## Summary",
        "",
        f"- Bodies: {summary['bodies']}",
        f"- Samples: {summary['samples']}",
        f"- Mean position diff (m): {summary.get('mean_diff_m')}",
        f"- Max position diff (m): {summary.get('max_diff_m')}",
        f"- Mean angular error (mas): {summary.get('mean_angular_mas')}",
        f"- Max angular error (mas): {summary.get('max_angular_mas')}",
        "",
        "## Samples",
        "",
        "| Body | UTC | jdTdb | diff (m) | angular (mas) |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in samples:
        diff = "—" if s.diff_magnitude_m is None else f"{s.diff_magnitude_m:.3e}"
        ang = "—" if s.angular_error_mas is None else f"{s.angular_error_mas:.3f}"
        md_lines.append(
            f"| {s.body_key} | {s.utc_iso} | {s.jd_tdb:.3f} | {diff} | {ang} |"
        )
    md_path = out_dir / "validation.md"
    md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")

    return json_path, md_path


def synthetic_validation_samples() -> list[ValidationSample]:
    """Generate a synthetic placeholder dataset (no Horizons / DE440 calls).

    Real validation is wired by Work 12 P2 deploy script. This serves as a
    fixture for unit tests + the dev demo dashboard.
    """
    out: list[ValidationSample] = []
    for body_key, _ in VALIDATION_TARGETS:
        for utc_iso in VALIDATION_TIMES:
            de440 = (1e11, 0.0, 0.0)
            horizons = (1e11 + 1.5, 0.0, 0.0)  # synthetic 1.5 m offset
            out.append(
                ValidationSample(
                    body_key=body_key,
                    utc_iso=utc_iso,
                    jd_tdb=2_451_545.0,
                    de440_position_m=de440,
                    horizons_position_m=horizons,
                    diff_magnitude_m=diff_magnitude_m(de440, horizons),
                    angular_error_mas=angular_separation_mas(de440, horizons),
                )
            )
    return out
